# mkdocs.yml
# Project information
site_name: ml-with-fastapi
site_author: Fahim Rustamy
site_description: >-
  Fulstack ML with fastapi, and postgress SQL
# Repository
repo_name: RustamyF/nlp-fastapi-fulstack
repo_url: https://github.com/RustamyF/nlp-fastapi-fulstack

theme:
  name: "material"
  features:
    - content.code.annotate

nav:
  - index.md




markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/frustamy
